from RandomNamesGenerator import RandomNamesGenerator as RNG
import copy
from datetime import datetime
from faker import Faker
from dateutil import relativedelta
from random import Random
import pandas
import calendar

RG = Random()

num_rows = 172
lists_percentage = 40
dt = datetime.now().strftime("%d-%m-%Y_%H-%M-%S")
source_dir = "./CSV/"
target_dir = "./test-data/"
target_file = f"Depatures-{num_rows}-rows-{dt}"
fnames_source_file = "FirstNames-Popularity-fr.csv"
fnames_target_file = f"FirstNames-Popularity-fr-{dt}.csv"
fnames_drop_columns = ["Popularity"]

fnames_rename_columns = {'FirstName': 'Prénom', 'Gender': 'Sexe'}

fnames_sort_columns = ["Popularity"]
fnames_final_order = ["Prénom", "Sexe", "Popularity"]
fnames_columns_order = ["Popularity", "Sexe", "Prénom"]

lnames_source_file = "LastNames-Popularity-fr.csv"
lnames_target_file = f"LaststNames-Popularity-fr-{dt}.csv"
lnames_drop_columns = ["Popularity"]

lnames_rename_columns = {'patronyme': 'Patronym', 'LastNameCount': 'Popularity'}

lnames_sort_columns = ["Popularity"]
lnames_final_order = ["Patronym", "Popularity"]
lnames_columns_order = ["Popularity", "Patronym"]

roles_source_file = "role-proffessionnels.csv"

roles = ["Actuarial Manager",
         "Actuary",
         "Adjuster",
         "Administrative",
         "Administrative Assistant",
         "Administrative Assistant",
         "Administrative Assistant",
         "Administrative Assistant",
         "Administrative Assistant",
         "Administrative Coordinator",
         "Administrative Job Titles",
         "Administrative Medical Assistant",
         "Administrative Services Manager",
         "Administrative Services Officer",
         "Administrative Support Manager",
         "Administrative Support Supervisor",
         "Administrator",
         "Administrator",
         "Administrator for Nonprofit Organizations",
         "Admissions Director",
         "Adolescent Specialist",
         "Adoption Specialist",
         "Advanced Psychiatric Nurse",
         "Advertising",
         "Advertising Agent",
         "Advertising Assistant",
         "Advertising Buyer",
         "Advertising Campaign Manager",
         "Advertising Coordinator",
         "Advertising Copywriter",
         "Advertising Job Titles",
         "Advertising Manager",
         "Advertising Sales Assistant",
         "Advertising Sales Director",
         "Advertising Sales Representative",
         "Advertising Specialist",
         "Advocacy Director",
         "Aerospace Engineer",
         "Agency Account Coordinator",
         "Agent",
         "Agricultural Engineer",
         "Aides Supervisor",
         "Air Traffic Controllers",
         "Aircraft Mechanic",
         "Aircraft Pilot",
         "Airport Operations Crew Member",
         "Allocation Analyst",
         "Amusement Ride Attendant",
         "an employee sponsor or advocate and",
         "Analyst",
         "Analyst",
         "Analyst",
         "Analytical Lab Technician",
         "Analytical Services Chemist",
         "Anesthesiologist",
         "Animal Researcher",
         "Animator",
         "Announcer",
         "Application Engineer",
         "Applications Engineer",
         "Appraisal Manager",
         "Appraiser",
         "Appraiser",
         "Apprentice",
         "Arbitrator",
         "Arson Investigator",
         "Art Director",
         "Art Director",
         "Assembler",
         "Assembly Supervisor",
         "Assembly Supervisor",
         "Assessor",
         "Assistant",
         "Assistant Account Executive",
         "Assistant Broker",
         "Assistant Buyer",
         "Assistant Director",
         "Assistant Director of Finance",
         "Assistant Director of Financial Operations",
         "Assistant Editor",
         "Assistant Field Technician",
         "Assistant Media Planner",
         "Assistant Plant Manager",
         "Assistant Project Manager",
         "Assistant Technician",
         "Associate Broker",
         "Associate Pastor",
         "Associate Producer",
         "Attorney",
         "Audio and Video Equipment Technician",
         "Audit Supervisor",
         "Auditor",
         "Auditor",
         "Auditor",
         "Author",
         "Automotive Engineer",
         "Aviation Psychologist",
         "Babysitter",
         "Back Office Assistant",
         "Back Office Supervisor",
         "Backwaiter",
         "Banquet Manager",
         "Banquet Server",
         "Bar Staff",
         "Bartender",
         "Bartender",
         "Baseball Umpire for Little League",
         "Basketball Referee for Juniors",
         "Bell Attendant",
         "Bellhop",
         "Bellman",
         "Bellperson",
         "Benefits Officer",
         "Bereavement Coordinator",
         "Best Second Jobs",
         "Billing Clerk",
         "Billing Manager",
         "Billing Specialist",
         "Biological Engineer",
         "Biologist",
         "Biomedical Engineer",
         "Biomedical Technician",
         "Blogger",
         "Blogger",
         "Boiler Engineer",
         "Boilermaker",
         "Bookbinders and bindery workers",
         "Bookkeeper",
         "Bookkeeper",
         "Branch Manager",
         "Brand Ambassador",
         "Brand Manager",
         "Bricklayer",
         "Broadcast Account Manager",
         "Broadcast and Sound Engineering Technician",
         "Broadcast News Analyst",
         "Broadcaster",
         "Broker",
         "Broker",
         "Budget Analyst",
         "Budget Analyst",
         "Budget Analyst",
         "Budget Manager",
         "Building and Grounds Supervisor",
         "Building Inspector",
         "Building Inspector",
         "Bursar",
         "Bus Driver",
         "Business",
         "Business Analyst",
         "Business Analyst",
         "Business Analyst",
         "Business Job Titles",
         "Business Office Supervisor",
         "Business System Analyst",
         "Busser",
         "Busser",
         "Buyer",
         "Buyer Trainee",
         "Cafe Manager",
         "Camera Operator",
         "Camp Counselor",
         "Camp Counselor in Training",
         "Campaign Manager",
         "Captain",
         "Car Wash Attendant",
         "Cargo Surveyor",
         "Carpenter",
         "Carpenter",
         "Case Management Aide",
         "Case Manager",
         "Case Manager",
         "Case Manager",
         "Case Manager",
         "Case Worker",
         "Cash Manager",
         "Cashier",
         "Catering Manager",
         "Catering Sales Manager",
         "Ceramics Engineer",
         "Certified Financial Planner",
         "Certified Medical Assistant",
         "Certified Nurse Assistant",
         "Certified Nursing Assistant",
         "Certified Pharmacy Technician",
         "Certified Public Accountant",
         "Chaplain",
         "Chapter Relations Administrator",
         "Charge Nurse",
         "Chartered Wealth Manager",
         "Chauffeur",
         "Chef",
         "Chef",
         "Chemical Dependency Counselor",
         "Chemical Dependency Director",
         "Chemical Engineer",
         "Chemical Plant Operator",
         "Chemical Technician",
         "Chief Accounting Officer",
         "Chief Association Executive",
         "Chief Engineer",
         "Chief Executive Officer",
         "Chief Financial Officer",
         "Chief Financial Officer",
         "Chief Financial Officer",
         "Chief Information Officer",
         "Chief Manufacturing Executive",
         "Chief Quality Control Executive",
         "Chief Technology Officer",
         "Child Advocate",
         "Child Care Assistant",
         "Child Care Provider",
         "Child Care Worker",
         "Child Care Worker",
         "Child Life Specialist",
         "Child Psychologist",
         "Child Support Case Officer",
         "Child Support Officer",
         "Childbirth Educator",
         "Civil Engineer",
         "Civil Engineer",
         "Civil Engineering Supervisor",
         "Claims Adjuster",
         "Claims Adjuster",
         "Claims Adjuster",
         "Claims Analyst",
         "Claims and Insurance Analyst",
         "Claims Examiner",
         "Claims Examiner",
         "Claims Manager",
         "Claims Representative",
         "Claims Specialist",
         "Clerk",
         "Clerk",
         "Clerk",
         "Client Advocate",
         "Client Relations Manager",
         "Client Strategist",
         "Client Support Specialist",
         "Climate Data Analyst",
         "Clinical Data Research",
         "Clinical Facilities Planning Manager",
         "Clinical Pharmacy Assistant",
         "Clinical Research Associate",
         "Clinical Research Associate",
         "Clinical Research Coordinator",
         "Clinical Research Coordinator",
         "Clinical Research Director",
         "Clinical Specialist",
         "Closing Agent",
         "Closing Coordinator",
         "CNC Machinist",
         "Cnc Operator",
         "Coach",
         "Coder",
         "Coding Educator",
         "College Admissions Counselor",
         "College Admissions Officer",
         "College Recruiter",
         "Comedian",
         "Commercial Appraiser",
         "Commercial Real Estate Agent",
         "Commercial Real Estate Broker",
         "Commercial Real Estate Broker",
         "Commissioning Engineer",
         "Communication Specialist",
         "Communications Coordinator",
         "Communications Coordinator",
         "Communications Director",
         "Communications Director",
         "Communications Director",
         "Communications Editor",
         "Communications Manager",
         "Communications Representative",
         "Communications Specialist",
         "Community Coordinator",
         "Community Counselor",
         "Community Health Director",
         "Community Manager",
         "Community Organizer",
         "Community Outreach Advocate",
         "Community Outreach Specialist",
         "Community Outreach Worker",
         "Community Planner",
         "Community Relations Director",
         "Community Service Project Coordinator",
         "Community Support Specialist",
         "Community Support Worker",
         "Companion for the Elderly",
         "Compliance Auditor",
         "Compliance Coordinator",
         "Compliance Director",
         "Compliance Engineer",
         "Compliance Investigator",
         "Compliance Technician",
         "Component Engineer",
         "Computer and Information  Systems Manager",
         "Computer Control Programmer/Operator",
         "Computer Hardware Engineer",
         "Computer Programmer",
         "Computer Programmer",
         "Computer Software Engineer",
         "Computing Consultant",
         "Concession Worker",
         "Concierge",
         "Concierge Agent",
         "Conciliator",
         "Concrete and Terrazzo Finisher",
         "Concrete Laborers",
         "Configuration Analyst",
         "Conflict Resolution Specialist",
         "Conservation Technician",
         "Construction",
         "Construction Assistant",
         "Construction Coordinator",
         "Construction Engineer",
         "Construction Engineer",
         "Construction Foreman",
         "Construction Job Titles",
         "Construction Manager",
         "Construction Superintendent",
         "Construction Supervisor",
         "Construction Worker",
         "Construction Worker",
         "Consultant",
         "Consultant",
         "Consultant",
         "Consultant",
         "Consulting Analyst",
         "Content Engineer",
         "Content Manager",
         "Content Manager",
         "Content Strategist",
         "Contract Administrator",
         "Contract Administrator",
         "Contract Administrator",
         "Contract Analyst",
         "Contract Drafting Legal Specialist",
         "Contract Engineer",
         "Contract Manager",
         "Contracts and Financial Compliance Manager",
         "Controller",
         "Controller",
         "Controller",
         "Controls Engineer",
         "Controls Engineer",
         "Cook",
         "Coordinator",
         "Copy Associate",
         "Copy Center Professional",
         "Copy Editor",
         "Copy Editor",
         "Copy Writer",
         "Copy Writer",
         "Copywriter",
         "Copywriter",
         "Corporate",
         "Corporate Accountant",
         "Corporate Communications Specialist",
         "Corporate Giving Director",
         "Corporate Giving Manager",
         "Corporate Job Titles",
         "Corporate Safety Director",
         "Corporate Sales Manager",
         "Correctional Officer",
         "Correctional Probation Officer",
         "Correctional Treatment Specialist",
         "Correctional Treatment Specialist",
         "Corrections Officer",
         "Corrections Unit Supervisor",
         "Cost Accountant",
         "Cost Engineer",
         "Counseling Psychologist",
         "Counselor",
         "Counselor",
         "Counselor",
         "Counselor",
         "Counselor In Training",
         "Court Advocate",
         "Court Messenger",
         "Court Reporter",
         "Court Representative",
         "Court Transcriptionist",
         "Craft Creator",
         "Crane Operator",
         "Creative Director",
         "Creative Director",
         "Creative Project Manager",
         "Credit Analyst",
         "Credit Analyst",
         "Credit Clerk",
         "Credit Manager",
         "Crew Member",
         "Criminal Investigator",
         "Crisis Counselor",
         "Crisis Therapist",
         "Critical Care Director",
         "Custodial Manager",
         "Customer Service Agent",
         "Customer Service Associate",
         "Customer Service Manager",
         "Customer Service Rep",
         "Customer Service Representative",
         "Customer Service Representative",
         "Customer Service Representative",
         "Dairy Processing Equipment Operator",
         "Dairy Processing Equipment Repairer",
         "Damage Appraiser",
         "Data Entry",
         "Database Administrator",
         "Database Coordinator",
         "Deck Officer",
         "Deckhand",
         "Delinquency Prevention Officer",
         "Dental Hygienist",
         "Dentist",
         "Deputy Fire Marshal",
         "Design Engineer",
         "Design Engineer",
         "Designer",
         "Designer",
         "Development Assistant",
         "Development Associate",
         "Development Coordinator",
         "Development Director",
         "Development Director",
         "Development Manager",
         "Development Officer",
         "Development Officer",
         "Development Technologist",
         "Developmental Psychologist",
         "Dietitian",
         "Digital Advertising Sales Manager",
         "Digital Advertising Specialist",
         "Digital Communications Professional",
         "Digital Content Manager",
         "Digital Media Manager",
         "Digital Media Planner",
         "Digital Media Specialist",
         "Digital Media Supervisor",
         "Direct of Real Estate",
         "Director",
         "Director of Development",
         "Director of Engineering",
         "Director of Events",
         "Director of External Affairs",
         "Director of Family Shelter",
         "Director of Financial Operations",
         "Director of Government Relations",
         "Director of Hotel Operations",
         "Director of Hotel Sales",
         "Director of Maintenance",
         "Director of Marketing",
         "Director of Nursing",
         "Director of Operations",
         "Director of Operations",
         "Director of Professional Services",
         "Director of Public Relations",
         "Director of Quality Management",
         "Director of Rehabilitation",
         "Director of Safety and Wellness",
         "Director of Sales",
         "Director of Social Media",
         "Director of Social Media Communications",
         "Director of Social Media Strategy",
         "Dishwasher",
         "Dishwasher",
         "Dispatcher",
         "Distribution Center Manager",
         "Distribution Director",
         "Distribution Manager",
         "Distribution Manager",
         "District Technical Service Manager",
         "Division Manager",
         "Division Manager",
         "Doctor",
         "Document Coder",
         "Dog Walker",
         "Drafting Technician",
         "Drilling Engineer",
         "Driver",
         "Driver/Sales Representative",
         "Driver/Sales Workers",
         "Driveway Sealer",
         "Drug Evaluator",
         "Drugstore Cashier",
         "Dry Wall Finisher",
         "Dry wall Installer",
         "E/M Engineer",
         "EBay Reseller",
         "Editor",
         "Editor",
         "Editorial Assistant",
         "Editorial Assistant",
         "Education Administrator",
         "Educational Psychologist",
         "Electric Home Appliance and Power Tool Repairer",
         "Electric Meter Installer and Repairer",
         "Electric Motor Assembler",
         "Electric/Electronics Technician",
         "Electrical Design Engineer",
         "Electrical Engineer",
         "Electrical Field Engineer",
         "Electrical Powerline Installer/Repairer",
         "Electrical Utility Trouble Shooter",
         "Electrician",
         "Electrician",
         "Electrician",
         "Electromechanical Technician",
         "Electronic Assembler",
         "Electronic Data Interchange Specialist",
         "Electronic Marketing Manager",
         "Electronic Technician",
         "Elementary School Teacher",
         "Elevator Installer/Repairer",
         "Emergency Medical Technician",
         "Employee Assistance Counselor",
         "Employment Interviewer",
         "Employment Recruiter",
         "Enforcement Officer",
         "Engagement Coordinator",
         "Engagement Manager",
         "Engineer",
         "Engineer",
         "Engineering",
         "Engineering Aide",
         "Engineering Clerk",
         "Engineering Executive",
         "Engineering Job Titles",
         "Engineering Manager",
         "Engineering Secretary",
         "Engineering Technician",
         "Entry Level",
         "Entry Level Engineer",
         "Environment Protection Specialist",
         "Environmental Auditor",
         "Environmental Compliance Engineer",
         "Environmental Data Analyst",
         "Environmental Emergencies Assistant",
         "Environmental Emergencies Planner",
         "Environmental Engineer",
         "Environmental Engineering Technician",
         "Environmental Health and Safety Delivery Specialist",
         "Environmental Health and Safety Engineer",
         "Environmental Health and Safety Manager",
         "Environmental Health Safety Engineer",
         "Environmental Health Specialist",
         "Environmental Project Analyst",
         "Environmental Protection Specialist",
         "Environmental Psychologist",
         "Environmental Quality Analyst",
         "Environmental Research Assistant",
         "Environmental Scientist",
         "Environmental Services Representative",
         "Environmental Specialist",
         "Epidemic Intelligence Service Officer",
         "Epidemiologist",
         "Equipment Director",
         "Equipment Engineer",
         "Equipment Operator",
         "Equipment Technician",
         "Ergonomist",
         "Estimating Manager",
         "Estimating Manager",
         "Estimating Manager",
         "Estimator",
         "Estimator",
         "Event Planner",
         "Event Planning",
         "Event Team Recruiter",
         "Events Manager",
         "Executive Assistant",
         "Executive Assistant",
         "Executive Assistant",
         "Executive Conference Manager",
         "Executive Director",
         "Executive Director of Nonprofit",
         "Executive Housekeeper",
         "Executive Meeting Manager",
         "Executive Producer",
         "Executive Services Administrator",
         "Expediter",
         "Expeditor",
         "Experimental Psychologist",
         "Exploration Director",
         "External Auditor",
         "External Communications Manager",
         "Facilities Director",
         "Facilities Engineer",
         "Facilities Management Executive",
         "Facilities Manager",
         "Facilities Planner",
         "Facilities Supervisor",
         "Facility Manager",
         "Family Advocacy Representative",
         "Family and Marriage Therapist",
         "Family Preservation Services Coordinator",
         "Family Therapist",
         "Farmhand",
         "Fast Food Worker",
         "Fiberglass Laminator/Fabricator",
         "Field Adjuster",
         "Field Engineer",
         "Field Operations Executive",
         "Field Operator",
         "Field Promotion Coordinator",
         "Field Safety Officer",
         "Field Service Coordinator",
         "Field Service Engineer",
         "Field Service Technician",
         "Field Technician",
         "File Clerk",
         "Film/Video Editor",
         "Finance",
         "Financial Aid Counselor",
         "Financial Aid Director",
         "Financial Aid Representative",
         "Financial Analyst",
         "Financial Analyst",
         "Financial Analyst",
         "Financial Analyst",
         "Financial Analyst",
         "Financial Assurance Manager",
         "Financial Assurance Specialist",
         "Financial Public Relations Associate",
         "Fire and Explosion Investigator",
         "Fire Fighter",
         "Fire Inspector",
         "Fire Investigator",
         "Fire Marshall",
         "Fire Prevention Inspector",
         "Fire Prevention Specialist",
         "Fire Protection Engineer",
         "Firmware Engineer",
         "First",
         "Fish and Game Warden",
         "Flea Market Seller",
         "Fleet Manager",
         "Flight Engineer",
         "Flight Instructor",
         "Floor Assembler",
         "Floor Assembly Supervisor",
         "Floor Technician",
         "Food and Beverage Manager",
         "Food Prep Worker",
         "Food Runner",
         "Food Server",
         "Food Service Worker at Nursing Home",
         "Food Technologist",
         "Foreclosure Specialist",
         "Forensic Accountant",
         "Forensic Case Monitor",
         "Fork Lift Operator",
         "Foster Care Therapist",
         "Foundation Director",
         "Framing Carpenter",
         "Freelance Data Entry",
         "Freelance Graphic Designer",
         "Freelance Programmer/APP Developer",
         "Freelance Web Designer",
         "Freelance Writer",
         "Freelance Writer",
         "Front Desk Agent",
         "Front Desk Associate",
         "Front Desk Clerk",
         "Front Desk Sales and Service Associate",
         "Front Office Associate",
         "Front Office Associate",
         "Front Office Attendant",
         "Front Office Help",
         "Front Office Supervisor",
         "Frontend Engineer",
         "Fundraising Coordinator",
         "Fundraising Manager",
         "Fundraising Manager",
         "General Laborer",
         "General Laborer",
         "General Laborer",
         "General Maintenance Worker",
         "General Manager",
         "General Manager",
         "General Office Clerk",
         "Genetic Counselor",
         "Geography",
         "Geological Engineer",
         "Gift Administration Specialist",
         "Gift Assurance Officer",
         "Golf Caddy",
         "Government Accountant",
         "Government Auditor",
         "Grant Administrator",
         "Grant Coordinator",
         "Grant Proposal Manager",
         "Grant Writer",
         "Grant/Contracts Specialist",
         "Grants and Contracts Assistant",
         "Grants and Contracts Specialist",
         "Grants/Proposal Writer",
         "Graphic Artist",
         "Graphic Designer",
         "Graphic/Web Designer",
         "Grassroots Organizer",
         "Greeter",
         "Grief Counselor",
         "Grinder",
         "Groundskeeper",
         "Groundwater Technician",
         "Group Sales Coordinator",
         "Group Sales Manager",
         "Guest Room Sales Manager",
         "Guest Service Representative",
         "Guest Services Associate",
         "Guest Services Coordinator",
         "Guest Services Manager",
         "Guidance Counselor",
         "Guidance Counselor",
         "Hardware Designer",
         "Hardware Engineer",
         "Head of Housekeeping",
         "Health and Safety Engineer",
         "Health and Safety Manager",
         "Health Care / Medical",
         "Health Care / Medical Job Titles",
         "Health Educator",
         "Health Research Assistant",
         "Health Technology Assistant",
         "Health/Safety",
         "Health/Safety Job Titles",
         "Healthcare Administrator",
         "Healthcare Management",
         "Healthcare or medical",
         "Hedge Fund Manager",
         "Hedge Fund Principal",
         "Hedge Fund Trader",
         "Helicopter Pilot",
         "Help Desk Technician",
         "HIV Mental Health Coordinator",
         "Home Health Aide",
         "Home Health Worker",
         "Home Inspector",
         "Hospice Administrator",
         "Hospice Supervisor",
         "Hospital Accounting Analyst",
         "Hospital Research Assistant",
         "Hospitality",
         "Hospitality Job Titles",
         "Host",
         "Hostess",
         "Hotel Deposit Clerk",
         "Hotel Front Desk Clerk",
         "Hotel Group Sales Manager",
         "House Cleaner",
         "Household Chores",
         "Housekeeper",
         "Housekeeper",
         "Housekeeper Aide",
         "Housekeeping Dispatcher",
         "Housekeeping Manager",
         "Housekeeping Supervisor",
         "Housekeeping Supervisor",
         "Housing Coordinator",
         "Housing Counselor",
         "Housing Program Manager",
         "Human Factors Psychologist",
         "Human Resources",
         "Human Resources Advisor",
         "Human Resources Assistant",
         "Human Resources Manager",
         "Human Service Worker",
         "Human Services Worker",
         "HVAC Mechanic",
         "I&C Engineer",
         "Import/Export Clerk",
         "Import/Export Manager",
         "Import/Export Supervisor",
         "Industrial Accountant",
         "Industrial Cleaner",
         "Industrial Engineer",
         "Industrial Engineer",
         "Industrial Engineering Technician",
         "Industrial Hygiene/Safety Engineer",
         "Industrial Hygienist",
         "Industrial Tractor Operator",
         "Infection Control Practitioner",
         "Information and Referral Specialist",
         "Information Clerk",
         "Information Technology Audit Manager",
         "Information Technology Auditor",
         "Information Technology Director",
         "Information Technology Manager",
         "Injury/Safety Hazard Assessment",
         "Inspector",
         "Inspector",
         "Inspector",
         "Inspector",
         "Installation & Maintenance Executive",
         "Installation & Maintenance Technician Director",
         "Institutional Research Director",
         "Instrumentation Engineer",
         "Insurance",
         "Insurance Adjuster",
         "Insurance Adjuster",
         "Insurance Agent",
         "Insurance Agent",
         "Insurance Appraiser",
         "Insurance Broker",
         "Insurance Claims Examiner",
         "Insurance Investigator",
         "Insurance Job Titles",
         "Insurance Representative",
         "Interactive Media Associate",
         "Interactive Media Buyer",
         "Interactive Media Buyer",
         "Interactive Media Coordinator",
         "Interactive Media Manager",
         "Interactive Media Planner",
         "Interactive Media Planner",
         "Interface Designer",
         "Interior Aircraft Assembly Manager",
         "Internal Auditor",
         "Internet Advertising Buyer",
         "Internet Marketing Coordinator",
         "Internet Marketing Manager",
         "Intranet Applications Manager",
         "Intranet Applications Specialist",
         "Intranet Specialist",
         "Intranet Support",
         "Inventory Control Analyst",
         "Inventory Control Clerk",
         "Inventory Control Manager",
         "Inventory Control Supervisor",
         "Investigator",
         "Investigator",
         "Investment Advisor",
         "Investment Banker",
         "Investor Relations Officer",
         "Iron Worker",
         "IT",
         "IT Analyst",
         "IT Support Staff",
         "Jailer",
         "Janitor",
         "Java Developer",
         "Jig and Fixture Builder",
         "Job Coach",
         "Job Developer",
         "Joiner",
         "Journalist",
         "Journalist",
         "Judge",
         "Junior Accountant",
         "Junior Analyst",
         "Junior Chemist",
         "Junior Engineer",
         "Junior Engineer",
         "Jury Consultant",
         "Juvenile Counselor",
         "Kennel Assistant",
         "Kitchen Team Member",
         "Labor Union Organizer",
         "Laboratory Assistant",
         "Laboratory Instructor",
         "Laboratory Technician",
         "Laborer",
         "Landscaper",
         "Landscaper",
         "Laundry Attendant",
         "Law Firm Administrator",
         "Lawn Mower/Landscaper",
         "Lawn Service Manager",
         "Lawyer",
         "Lawyer",
         "Lead Engineer",
         "Lead Housekeeper",
         "Legal",
         "Legal Aide/Assistant",
         "Legal Analyst",
         "Legal Job Titles",
         "Legal Nurse Consultant",
         "Legal Records Manager",
         "Legal Secretary",
         "Legal Secretary",
         "Legal Services Director",
         "Leveraged Buyout Investor",
         "Licensed Practical Nurse",
         "Licensed Real Estate Appraiser",
         "Licensed Sales Consultant",
         "Licensing Engineer",
         "Life Skills Counselor",
         "Lifeguard",
         "Lifeguard",
         "Line Producer",
         "Lineman",
         "List of Best Entry Level Jobs",
         "List of First Job Ideas",
         "Litigation Docket Manager",
         "Litigation Support Director",
         "Living Skills Advisor",
         "Loan Documents Closer",
         "Loan Documents Coordinator",
         "Loan Officer",
         "Loan Processor",
         "Loan Underwriter",
         "Lobbyist",
         "Lobbyist",
         "Locksmith",
         "Locomotive Engineer",
         "Logistics Analyst",
         "Logistics Coordinator Jobs",
         "Logistics Engineer",
         "Logistics Manager",
         "Logistics Specialist",
         "Loss Control Consultant",
         "Loss Control Consultant/Specialist",
         "Loss Control Specialist",
         "Machine Operator",
         "Machine Shop Maintenance Supervisor",
         "Machine Shop Production Supervisor",
         "Machine Tool Cutting Operator/Tender",
         "Machinists",
         "Magistrate",
         "Mail Clerk",
         "Mail Clerk Leader",
         "Mail Equipment Operator",
         "Mailroom Personnel",
         "Maintenance",
         "Maintenance Engineer",
         "Maintenance Job Titles",
         "Maintenance Planner",
         "Maintenance Supervisor",
         "Major Account Manager",
         "Major Gifts Officer",
         "Managed Care Coordinator",
         "Management Accountant",
         "Management Information Systems Director",
         "Manager",
         "Manager",
         "Manager Digital and Social Media",
         "Manager of Customer Billing",
         "Manager of Engineering",
         "Manager or Supervisor",
         "Managerial Accountant",
         "Managing Editor",
         "Managing Editor",
         "Manufacturing",
         "Manufacturing Engineer",
         "Manufacturing Engineer",
         "Manufacturing Job Titles",
         "Manufacturing Process Engineer",
         "Manufacturing Production Manager",
         "Manufacturing Technician",
         "Manufacturing/Production Technician",
         "Marine Cargo Inspector",
         "Marine Cargo Surveyor",
         "Marine Engineer",
         "Marine Oiler",
         "Marine Surveyor",
         "Market Access Analyst",
         "Market Access Associate",
         "Marketing Analyst",
         "Marketing Assistant",
         "Marketing Assistant",
         "Marketing Associate",
         "Marketing Communications Director",
         "Marketing Communications Manager",
         "Marketing Consultant",
         "Marketing Coordinator",
         "Marketing Coordinator",
         "Marketing Coordinator",
         "Marketing Coordinator",
         "Marketing Director",
         "Marketing Manager",
         "Massage Therapist",
         "Master Electrician",
         "Master Plumber",
         "Master Scheduler",
         "Material Handler",
         "Materials Control Manager",
         "Materials Engineer",
         "Materials Handler",
         "Materials Handling Supervisor",
         "Materials Management Supervisor",
         "Materials Manager",
         "Materials Planner",
         "Materials Planner",
         "Mechanic",
         "Mechanical Design Engineer",
         "Mechanical Designer",
         "Mechanical Engineer",
         "Mechanical Engineer",
         "Mechanical Technician",
         "Media",
         "Media and Communication Equipment Operator",
         "Media and Communications Manager",
         "Media Coordinator",
         "Media Coordinator",
         "Media Director",
         "Media Director",
         "Media Job Titles",
         "Media Planner",
         "Media Planner",
         "Media Product Development Manager",
         "Media Relations Manager",
         "Media Research Analyst",
         "Media Specialist",
         "Media Specialist",
         "Mediator",
         "Mediator",
         "Medical Administrative",
         "Medical Assistant",
         "Medical Assistant or phlebotomist",
         "Medical Assistant or receptionist",
         "Medical Biller",
         "Medical Billing Service",
         "Medical Billing Specialist",
         "Medical Claims and Billing Specialist",
         "Medical Coder",
         "Medical Office Assistant",
         "Medical Office Manager",
         "Medical Office Specialist",
         "Medical or Health Services Manager",
         "Medical Physics Researcher",
         "Medical Receptionist",
         "Medical Records Clerk",
         "Medical Research Assistant",
         "Medical Research Technician",
         "Medical Sales",
         "Medical Scientist",
         "Medical Secretary",
         "Medical Secretary",
         "Medical Services Assistant",
         "Medical Social Worker",
         "Medical Technician",
         "Medical Technologist",
         "Medical Transcriber",
         "Medical Transcriptionist",
         "Medical Transcriptionist",
         "Meeting Concierge",
         "Meeting Coordinator",
         "Meeting Manager",
         "Meeting Specialist",
         "Member Certification Manager",
         "Member Records Administrator",
         "Member Services Director",
         "Member Services Representative",
         "Membership Assistant",
         "Membership Coordinator",
         "Mental Health Aide",
         "Mental Health Coordinator",
         "Mental Health Counselor",
         "Merchandising Manager",
         "Merchant Mariners",
         "Metal workers",
         "Metallurgical Engineer",
         "Microbiologist",
         "Military Psychologist",
         "Millwright",
         "Millwright",
         "Mining Engineer",
         "Mining Safety Engineer",
         "Minister",
         "Mortgage Advisor",
         "Mortgage Banker",
         "Mortgage Consultant",
         "Mortgage Coordinator",
         "Mortgage Loan Processor",
         "Mortgage Loan Underwriter",
         "Mortgage Professional",
         "Mortgage Specialist",
         "Motion Picture Set Worker",
         "Motor Racer",
         "Motorboat Operator",
         "Multi Media Advertising Sales Manager",
         "Multi Media Sales Manager",
         "Multimedia Designer",
         "Multimedia Services Manager",
         "Multimedia Specialist",
         "Music Teacher for Young Children",
         "Music Therapist",
         "Musical Performer",
         "Mutual Fund Analyst",
         "Mystery Shopper",
         "National Account Coordinator",
         "Naval Architect",
         "Network Architect",
         "Network Engineer",
         "Network Engineer",
         "Network Engineer",
         "Network System Administrator",
         "Neurologist",
         "News Analysts",
         "Night Auditor",
         "Night Clerk",
         "Night School Teacher",
         "Non Profit",
         "Non Profit Job Titles",
         "Nonprofit Fundraiser",
         "Nuclear Engineer",
         "Nurse",
         "Nurse Practitioner",
         "Nursery Worker",
         "Nursing Home Administrator",
         "Nursing Home Administrator",
         "Nutritionist",
         "Occupational Health Analyst",
         "Occupational Health Nurse",
         "Occupational Therapist",
         "Occupational Therapist",
         "Office Assistant",
         "Office Clerk",
         "Office Manager",
         "Office Manager",
         "Office Manager",
         "Office Support Manager",
         "Office Support Supervisor",
         "Online Activist",
         "Online Advertising Coordinator",
         "Online Advertising Director",
         "Online Advertising Manager",
         "Online Advertising Specialist",
         "Online Content Coordinator",
         "Operations Analyst",
         "Operations Clerk",
         "Operations Clerk",
         "Operations Engineer",
         "Operations Manager",
         "Operations Manager",
         "Operations Manager",
         "Operations Manager",
         "Operations Research Analysis Manager",
         "Operations Research Analyst",
         "Operations Section Manager",
         "Operations Supervisor",
         "Operations Team Leader",
         "Operations Unit Manager",
         "Operator",
         "Orderly Attendant",
         "Organic Lab Research Assistant",
         "Organic Lab Worker",
         "Outpatient Health Specialist",
         "Packaging Engineer",
         "Packaging Engineer",
         "Packaging Engineer",
         "Painter",
         "Painter",
         "Painter",
         "Painting and Coating Worker",
         "Paper Delivery Person",
         "Paralegal",
         "Paramedic",
         "Parole Officer",
         "Pastor",
         "Patient Care Associate",
         "Patient Services Representative",
         "Patient Services Technician",
         "Payroll Manager",
         "Payroll Services Analyst",
         "Performance Engineer",
         "Pest Control Technician",
         "Pet Groomer",
         "Pet Sitter",
         "Pet Walker",
         "Petroleum Engineer",
         "Petroleum Inspector",
         "Pharmaceutical Assistant",
         "Pharmaceutical Marketing Assistant",
         "Pharmaceutical Research Analyst",
         "Pharmaceutical Research Assistant",
         "Pharmaceutical Research Technician",
         "Pharmaceutical Sales",
         "Pharmaceutical Sales Rep",
         "Pharmaceutical Sales Representative",
         "Pharmaceutical Technician",
         "Pharmacist",
         "Pharmacy Affairs Assistant",
         "Pharmacy Assistant",
         "Pharmacy Innovation Assistant",
         "Pharmacy Technician",
         "Phlebotomist",
         "Photo Editor",
         "Photographer",
         "Photographic Processor",
         "Physical Therapist",
         "Physical Therapist",
         "Physician",
         "Physician ",
         "Pilot",
         "Pipe Fitter",
         "Pipefitter",
         "Pipeline Engineer",
         "Pipeline Executive",
         "Pipeline Maintenance Manager",
         "Pipeline Operations Manager",
         "Pipeline Technician",
         "Pipelines Director",
         "Pipelines Manager",
         "Piping Engineer",
         "Piping Stress Engineer",
         "Planned Gift Director",
         "Planned Giving Director",
         "Planner",
         "Planning Engineer",
         "Planning Manager",
         "Plant Accountant",
         "Plant Engineer",
         "Plant Human Resources Manager",
         "Plant Manager",
         "Plant Operator",
         "Plastics Engineer",
         "Plumber",
         "Plumber",
         "Police Officer",
         "Police Officer",
         "Policy Analyst",
         "Policy Planning Specialist",
         "Portfolio Management Marketing",
         "Portfolio Manager",
         "Power Engineer",
         "Power Plant Operator",
         "Power Regulator",
         "Powerhouse Supervisor",
         "Powerhouse Supervisor",
         "Precision Assembler",
         "Preprint Analyst",
         "Print Traffic Coordinator",
         "Print Traffic Director",
         "Print Traffic Manager",
         "Printing Machine Operators",
         "Private Accountant",
         "Probation Officer",
         "Probation Officer",
         "Process Control Engineer",
         "Process Design Engineer",
         "Process Engineer",
         "Process Engineer",
         "Process Inspector",
         "Process Operator",
         "Process Research Manager",
         "Process/Product Design Engineer",
         "Processing Equipment Operations Supervisor",
         "Producer",
         "Product Design/Development Engineer",
         "Product Development Engineering Manager",
         "Product Engineer",
         "Product Manager",
         "Product Marketing Analyst",
         "Product Responsibility Liaison",
         "Product Safety Consultant",
         "Product Safety Engineer",
         "Product Safety Manager",
         "Product Test Specialist",
         "Production Artist",
         "Production Assistant",
         "Production Control Clerk",
         "Production Control Manager",
         "Production Engineer",
         "Production Engineering Manager",
         "Production Foreman",
         "Production Manager",
         "Production Painter",
         "Production Planner/Scheduler",
         "Production Scheduler",
         "Production Supervisor",
         "Production Supervisor",
         "Production Team Leader",
         "Production Technician",
         "Production Test Supervisor",
         "Production Worker",
         "Professional Programs Assistant",
         "Program Assistant",
         "Program Coordinator",
         "Program Coordinator",
         "Program Coordinator/Manager",
         "Program Director",
         "Program Director",
         "Program Manager",
         "Program Manager",
         "Program Manager",
         "Program Officer for Foundation",
         "Programmer",
         "Programmer",
         "Programmer Analyst",
         "Programmer Analyst",
         "Programmer or analyst",
         "Project Assistant",
         "Project Assistant",
         "Project Controls Engineer",
         "Project Coordinator",
         "Project Engineer",
         "Project Management",
         "Project Manager",
         "Project Manager",
         "Project Manager",
         "Project Manager",
         "Project Manager",
         "Project Manager",
         "Promotions Specialist",
         "Proofreader",
         "Property Manager",
         "Proposal Engineering Coordinator",
         "Protection Engineer",
         "Pruner",
         "Psychiatric Aide",
         "Psychiatric Aide",
         "Psychiatric Social Worker",
         "Psychiatric Social Worker",
         "Psychiatric Technician",
         "Psychological aide",
         "Psychology Related",
         "Public Accountant",
         "Public Affairs Specialist",
         "Public Health Manager",
         "Public Information Assistant",
         "Public Information Officer",
         "Public Information Specialist",
         "Public Opinion Surveyor",
         "Public Relations",
         "Public Relations Agent",
         "Public Relations Coordinator",
         "Public Relations Coordinator",
         "Public Relations Director",
         "Public Relations Director",
         "Public Relations Job Titles",
         "Public Relations Manager",
         "Public Relations Manager",
         "Public Relations Manager",
         "Public Relations Specialist",
         "Public Relations Specialist",
         "Public Transportation Inspector",
         "Publicist",
         "Publishing Agent",
         "Purchasing Agent/Buyer",
         "Purchasing Coordinator",
         "Quality Assistant",
         "Quality Assurance Engineer",
         "Quality Assurance Engineer",
         "Quality Assurance Manager",
         "Quality Assurance Manager",
         "Quality Assurance Technologist",
         "Quality Control Analyst",
         "Quality Control Analyst",
         "Quality Control Engineer",
         "Quality Control Inspector",
         "Quality Control Manager",
         "Quality Control Supervisor",
         "Quality Coordinator",
         "Quality Engineer",
         "Quality Engineer",
         "Quality Inspector",
         "Quality Manager",
         "R&D Engineer",
         "Radio Operator",
         "Rail Car Repairer",
         "Rail Yard Engineer",
         "Railroad Brake Operator",
         "Railroad Conductor",
         "Railroad Yard Worker",
         "Ratings Analyst",
         "Real Estate",
         "Real Estate Agent",
         "Real Estate Agent",
         "Real Estate Analyst",
         "Real Estate Appraiser",
         "Real Estate Appraiser",
         "Real Estate Associate",
         "Real Estate Attorney",
         "Real Estate Clerk",
         "Real Estate Consultant",
         "Real Estate Job Titles",
         "Real Estate Manager",
         "Real Estate Officer",
         "Real Estate Specialist",
         "Realty Specialist",
         "Receptionist",
         "Receptionist",
         "Receptionist",
         "Recording Engineer",
         "Records Management Analyst",
         "Recreational Therapist",
         "Recreational Therapy Director",
         "Recruiter",
         "Recruiting Assistant",
         "Refuse and Recyclable Material Collectors",
         "Regional Safety Manager",
         "Regional Sales Manager",
         "Registered Medical Assistant",
         "Registered Nurse",
         "Registered Nurse",
         "Regulatory Affairs Associate",
         "Regulatory Affairs Director",
         "Rehabilitation Counselor",
         "Rehabilitation Engineering Assistant",
         "Reimbursement Analyst",
         "Relationship Manager",
         "Relay Engineer",
         "Reliability Engineer",
         "Reliability Engineer",
         "Reporter",
         "Research Analyst",
         "Research and Development Associate",
         "Research and Development Director",
         "Research and Development Engineer",
         "Research and Development Manager",
         "Research and Development Supervisor",
         "Research and Development Technician",
         "Research and Development Tester",
         "Research Assistant",
         "Research Assistant",
         "Research Assistant",
         "Research Assistant",
         "Research Associate",
         "Research Associate",
         "Research Engineer",
         "Research Technician",
         "Research Technician",
         "Researcher",
         "Reservations Agent",
         "Reservoir Engineer",
         "Residential Appraiser",
         "Residential Living Assistant",
         "Residential Real Estate Agent",
         "Residential Real Estate Broker",
         "Restaurant Hostess/Host",
         "Restaurant Manager",
         "Restaurant Server",
         "Resteel Ironworker",
         "Retail Analyst",
         "Retail Loan Specialist",
         "Retail Management Trainee",
         "Retail Store Sales Clerk",
         "Retail Store Worker",
         "Revenue Cycle Administrator",
         "Revenue Cycle Manager",
         "Revenue Cycle Supervisor",
         "RF Engineer",
         "Right of Way Agent",
         "Risk Control Consultant",
         "Risk Control Representative",
         "Risk Management Coordinator",
         "Risk Manager",
         "Risk Manager",
         "Roofer",
         "Room Attendant",
         "Room Service Manager",
         "Room Service Worker",
         "Rotating Equipment Engineer",
         "Safety Director",
         "Safety Director",
         "Safety Engineer",
         "Safety Engineer",
         "Safety Manager",
         "Safety Manager",
         "Safety Manager/Coordinator",
         "Safety Technician",
         "Safety Technician",
         "Safety Technician",
         "Sailor",
         "Sales Agency Manager",
         "Sales Agent",
         "Sales Analyst",
         "Sales and Marketing Coordinator",
         "Sales Assistant",
         "Sales Assistant",
         "Sales Associate",
         "Sales Coordinator",
         "Sales Engineer",
         "Sales Manager",
         "Sales Manager",
         "Sales Planner",
         "Sales Rep",
         "Sales Representative",
         "Sales Trainee",
         "Satellite Data Analyst",
         "SCADA Engineer",
         "Scheduler",
         "Scheduler",
         "School Counselor",
         "Science",
         "Science Job Titles",
         "Science Technician",
         "Science Writer",
         "Scientific Artist",
         "Second",
         "Secondary School Teacher",
         "Secretary",
         "Secretary",
         "Section Editor",
         "Security Director",
         "Security Engineer",
         "Security Guard",
         "Security Guard",
         "Security Specialist",
         "Semiconductor Processor",
         "Senior Account Director",
         "Senior Administrative Analyst",
         "Senior Administrative Coordinator",
         "Senior Administrative Services Officer",
         "Senior Applications Engineer",
         "Senior Auditor",
         "Senior Budget Analyst",
         "Senior Buyer",
         "Senior Cash Management Analyst",
         "Senior Coordinator",
         "Senior Database Administrator",
         "Senior Electrical Engineer",
         "Senior Executive Assistant",
         "Senior Financial Analyst",
         "Senior General Audit Manager",
         "Senior Gift Assurance Officer",
         "Senior Grants and Contracts Specialist",
         "Senior Manufacturing Engineer",
         "Senior Mechanical Engineer",
         "Senior Negotiator",
         "Senior Network Architect",
         "Senior Network Engineer",
         "Senior Network System Administrator",
         "Senior Pharmacy Student",
         "Senior Process Engineer",
         "Senior Programmer",
         "Senior Programmer Analyst",
         "Senior Programmer Analyst",
         "Senior Security Specialist",
         "Senior Software Engineer",
         "Senior Special Events Coordinator",
         "Senior Strategic Planner",
         "Senior Support Assistant",
         "Senior Support Specialist",
         "Senior Support Specialist",
         "Senior System Administrator",
         "Senior System Analyst",
         "Senior System Architect",
         "Senior System Designer",
         "Senior Systems Analyst",
         "Senior Systems Software Engineer",
         "Senior Web Administrator",
         "Senior Web Developer",
         "Server",
         "Service Representative",
         "Shift Leader",
         "Shift Manager",
         "Shift Supervisor",
         "Shipping and Receiving Clerk",
         "Shipping and Receiving Manager",
         "Shipping and Receiving Supervisor",
         "Shuttle Car Operator",
         "Signal Worker",
         "Silicon Wafer Fabrication Operator",
         "Site Manager",
         "Snow Removal/Plowing",
         "Soccer Referee for Juniors",
         "Social and Human Service Assistant",
         "Social Media",
         "Social Media Account Executive",
         "Social Media Advertising Manager",
         "Social Media Analyst",
         "Social Media Assistant",
         "Social Media Associate",
         "Social Media Coordinator",
         "Social Media Designer",
         "Social Media Editor",
         "Social Media Job Titles",
         "Social Media Manager",
         "Social Media Manager",
         "Social Media Marketing Coordinator",
         "Social Media Specialist",
         "Social Media Specialist",
         "Social Media Specialist",
         "Social Media Specialist",
         "Social Media Strategist",
         "Social Services",
         "Social Services Aide",
         "Social Services Director",
         "Social Services Specialist",
         "Social Work",
         "Social Work Assistant",
         "Social Work Job Titles",
         "Social Work Manager",
         "Social Worker",
         "Social Worker",
         "Social Worker",
         "Software Consultant",
         "Software Developer",
         "Software Developer",
         "Software Engineer",
         "Software Engineer",
         "Software Engineer",
         "Software Engineer",
         "Software Engineering Assistant",
         "Software Quality Assurance Analyst",
         "Solid Waste Field Technician",
         "Sound Mixer",
         "Spares Coordinator",
         "Special Educator",
         "Special Events Coordinator",
         "Special Events Coordinator",
         "Special Events Director",
         "Special Programs Coordinator",
         "Special Projects Coordinator",
         "Staff Accountant",
         "Staff Assistant",
         "Staff Auditor",
         "Staff Engineer",
         "Staffing Coordinator",
         "Stage Hand",
         "Staking Engineer",
         "State Sales Manager",
         "Stationary Engineer",
         "Statistician",
         "Statistician",
         "Stockbroker",
         "Strategic Planner",
         "Strategic Planning and Institutional Analysis Manager",
         "Strategic Program Planning Advisor",
         "Streetcar Operator",
         "Structural Assembler",
         "Structural Engineer",
         "Structural Engineer",
         "Structural Ironworker",
         "Structural Metal fabricator",
         "Substance Abuse Counselor",
         "Substation Engineer",
         "Subway Operator",
         "Superintendent",
         "Supervisor",
         "Supervisor or manager",
         "Supplier Quality Engineer",
         "Supply Technician",
         "Support Assistant",
         "Support Services Director",
         "Support Specialist",
         "Support Specialist",
         "Surface Mount Technology Machine Operator",
         "Surgical Technologist",
         "Surveyor",
         "Surveyor",
         "System Administrator",
         "System Analyst",
         "System Architect",
         "System Designer",
         "System Safety Engineer",
         "Systems Analyst",
         "Systems Analyst",
         "Systems Engineer",
         "Systems Software Engineer",
         "Target Marketing Strategist",
         "Tax Accountant",
         "Tax Specialist",
         "Taxi Driver",
         "Teacher",
         "Teaching Music Lessons",
         "Team Leader",
         "Team Member",
         "Technical Producer",
         "Technical Specialist",
         "Technical Support Engineer",
         "Technical Support Technician",
         "Technical Writer",
         "Technical Writer",
         "Technical Writer",
         "Technical Writer",
         "Technology Research Analyst",
         "Technology Research Manager",
         "Technology Specialist",
         "Teen Center Director",
         "Telecommunications Engineer",
         "Telecommunications Specialist",
         "Telecommunications Technician",
         "Telemarketer",
         "Television Announcer",
         "Test Engineer",
         "Test Engineer",
         "Therapeutic Director",
         "Therapist",
         "Ticket Taker",
         "Title Coordinator",
         "Title Examiner",
         "Tool and Die Maker",
         "Tool Crib Attendant",
         "Tool Room Supervisor",
         "Top Distribution Executive",
         "Top Inventory Control Executive",
         "Total Quality Management Director",
         "Total Quality Manager",
         "Toxics Program Officer",
         "Traffic Clerk",
         "Traffic Director",
         "Traffic Manager",
         "Traffic Manager",
         "Traffic Supervisor",
         "Traffic/Rate Analyst",
         "Train Crew Member",
         "Training Manager",
         "Transcription",
         "Transcriptionist",
         "Translator",
         "Transmission Engineer",
         "Transmission Planning Engineer",
         "Transportation",
         "Transportation Coordinator",
         "Transportation Director",
         "Transportation Job Titles",
         "Transportation Manager",
         "Transportation Planner",
         "Transportation Project Manager",
         "Transportation Supervisor",
         "Travel Agent",
         "Travel Coordinator",
         "Travel Manager",
         "Treasurer",
         "Trial Consultant",
         "Truck Driver Supervisor",
         "Trust Officer",
         "Turbine Engineer",
         "Tutor",
         "Tutor",
         "Typist",
         "Ultrasonographer",
         "Underwriter",
         "Underwriter",
         "Underwriter",
         "Underwriter",
         "Underwriter Assistant",
         "Underwriting Manager",
         "University Psychology Professor",
         "Valet Attendant",
         "Valet Parker",
         "Valet Parking Attendant",
         "Validation Engineer",
         "Van Driver",
         "Vehicle Washer/Equipment Cleaner",
         "Vice President",
         "Vice President of Engineering",
         "Videographer",
         "Virtual Assistant",
         "Virtual Assistant",
         "Virtual Receptionist",
         "Vocational Rehabilitation Counselor",
         "Volunteer Coordinator",
         "Volunteer Director",
         "Volunteer Manager",
         "Volunteer Services Director",
         "Wafer Processing Technician",
         "Wait Staff",
         "Waiter",
         "Waiter/Waitress",
         "Waitress",
         "Warehouse Associate",
         "Warehouse Manager",
         "Warehouse Worker",
         "Warehouse Worker",
         "Waste Management Specialist",
         "Waste Treatment Plant Operator",
         "Waste Water Treatment Plant Manager",
         "Web Administrator",
         "Web Content Executive",
         "Web Customer Support Specialist",
         "Web Designer",
         "Web Developer",
         "Web Product Manager",
         "Web Systems Director",
         "Webmaster",
         "Webmaster",
         "Wedding Coordinator",
         "Wedding Photographer/Videographer",
         "Wedding Sales Manager",
         "Wedding/Party Planner",
         "Weekend Landscaper",
         "Welder",
         "Welder",
         "Welding Engineer",
         "What Job Titles Mean",
         "Woodworker",
         "Word Processor",
         "Writer",
         "Yardmaster",
         "Youth Counselor",
         "Youth Worker"]

service_lines = ["Management",
                 "Business et Digital transformation",
                 "Operation and product services",
                 "Digital transformation",
                 "Cloud First",
                 "Data Mastery",
                 "Agile"]

situations_futures = ["Autres ESN",
                      "Client final",
                      "Services & Conseil",
                      "Editeurs",
                      "Mutation externe",
                      "Changement de métier / réorientation",
                      "Activité freelance"]

motifs_departs = ["Perspectives d'évolution",
                  "Projet Personnel",
                  "Intérêt des missions",
                  "Rémunération",
                  "Ambiance/Environnement de travail",
                  "Changer de pays",
                  "Plus de Télétravail",
                  "Moins de Télétravail",
                  "Moins de déplacements",
                  "Méthodologie de Travail"]

sites = ["Tours",
         "Brest",
         "Lyon (Ivoire)",
         "Grenoble",
         "Nancy",
         "Aix",
         "Sophia",
         "Pau",
         "Rennes",
         "Montbonnot(Nov)",
         "Cesson(Spiréa)",
         "Pau (TS)",
         "Biot",
         "Aix-en-P.(Azur)"]

employment_situations = ["Création d'entreprise",
                        "Salarié dans le software",
                        "Micro Entreprenneur Software",
                        "Reconversion vers un nouveau metier",
                        "Parent au foyer",
                        "Industriel, artisan ou commerçant",
                        "Profession libérale",
                        "Cadre moyen ou supérieur",
                        "Salarié",
                        "Ouvrier",
                        "Personnel de services",
                        "Retraité",
                        "Sans activité professionnelle",
                        "En recherche d'emploi"]

padding_week_day = RG.randrange(2, 6)

FNG = RNG(source_dir, fnames_source_file) # RandomNamesGenerator for french first names

FirstNames_df = FNG.get_data()
FirstNames_percentage_rows = RNG.calculate_percentage_num_rows(FirstNames_df, lists_percentage)

if FirstNames_percentage_rows < num_rows:
    num_rows = FirstNames_percentage_rows

LNG = RNG(source_dir, lnames_source_file)

LastNames_df = LNG.get_data()
LastNames_percentage_rows = RNG.calculate_percentage_num_rows(LastNames_df, lists_percentage)

if LastNames_percentage_rows < num_rows:
    num_rows = LastNames_percentage_rows

FirstNames_df = RNG.prepare_data_frame(FNG, fnames_rename_columns, None, fnames_final_order, fnames_sort_columns, num_rows, lists_percentage, False)

first_names = FirstNames_df.Prénom.values.tolist()
first_names_low = list()

for _ in first_names:
    first_names_low.append(str(_).capitalize())

LastNames_df = RNG.prepare_data_frame(LNG, lnames_rename_columns, None, lnames_final_order, lnames_sort_columns, num_rows, lists_percentage, False)

last_names = LastNames_df.Patronym.values.tolist()
last_names_low = list()

for i in last_names:
    last_names_low.append(str(i).capitalize())

RLSG = RNG(source_dir, roles_source_file)

roles_df = RLSG.get_data()
# roles_percentage_rows = RLSG.calculate_percentage_num_rows(
# roles_df, lists_percentage)



career_mgrs = list()
for _ in range(15):
    career_mgr_fn = first_names_low[RG.randint(1, len(first_names_low) -1)]
    career_mgr_ln = last_names_low[RG.randint(1, len(last_names_low) -1)]
    career_mgrs.append(career_mgr_fn + " " + career_mgr_ln)

FirstNames_df.insert(0, "Nom", last_names_low)
FirstNames_df.drop(columns="Popularity", inplace=True)

GGID = list()

f = Faker('fr_FR')

for _ in range(num_rows):
    GGID.append(f.unique.numerify(text='%#######'))

date_format = "%d-%m-%Y"
now = datetime.now()
creation = datetime.strptime("01-10-1967", date_format)
cap_dob = str(creation.strftime(date_format))
dummy_date = datetime.strptime("13-06-1991", date_format)

dobs = list()
ages = list()
start_dates = list()
service_years = list()
site_postes = list()
services_posts = list()
grades = list()
roles_posts = list()
notice_dates = list()
exit_dates = list()
assigned_career_mgrs = list()
exit_interviews = list()
RRH_interviews = list()
reasons_for_leaving_1 = list()
reasons_for_leaving_2 = list()
strengths = list()
areas_for_improvement = list()
future_employment_situations = list()
commentaires_RRH = list()

for i in range(num_rows):
    # Date of Birth
    dob = f.date_of_birth(None, 19, 65)
    dobs.append(dob)

    # Age
    now_dob = relativedelta.relativedelta(now, dob)
    age = now_dob.years
    ages.append(age)

    ## Get a random start date on a business day at least 19 years after dob and 31 days before today.
    employable_from = datetime.fromordinal(dob.toordinal() + 6570)
    employable_to = datetime.fromordinal(now.toordinal() - 31)
 
    start_date = f.date_between(employable_from, employable_to)   

    if start_date.weekday() > 4:
        start_date = datetime.fromordinal(start_date.toordinal() + padding_week_day).date()

    start_dates.append(start_date)

    now_start = relativedelta.relativedelta(now, start_date)
    years_service = now_start.years
    service_years.append(years_service)

    # Set the BU site of the employee
    site = sites[RG.randint(1, len(sites) - 1)]
    site_postes.append(site)

    # Set the Service Line of the employee
    service_post = service_lines[RG.randint(1, len(service_lines) - 1)]
    services_posts.append(service_post)

    # Set the grade of the employee
    random_grade = RG.randint(0, num_rows)
    
    if i == random_grade:
        years_service = years_service - 5

    if years_service >= 0 and years_service <= 5:
        grade = "A"
    
    if years_service > 5 and years_service <= 10:
        grade = "B"
    
    if years_service > 10 and years_service <= 15:
        grade  = "C"
    
    if years_service > 15 and years_service <= 20:
        grade = "D"
    
    if years_service > 20 and years_service <= 25:
        grade = "E"
    
    if years_service > 25:
        grade = "F"

    grades.append(grade)

    # Set the role of the employee
    role_post = roles[RG.randint(1, len(roles) - 1)]
    roles_posts.append(role_post)

    # Set Date notice given
    noticeable_date = datetime.strptime(f"01-01-{now.year}", "%d-%m-%Y")
    if start_date.toordinal() > noticeable_date.toordinal():
        noticeable_date = start_date

    notice_day = f.date_between(noticeable_date, now.today())
    notice_dates.append(notice_day)

    expected_exit_start = datetime.fromordinal(notice_day.toordinal() + 31)
    expected_exit_end = datetime.fromordinal(notice_day.toordinal() + 123)
    exit_day = f.date_between(expected_exit_start, expected_exit_end)

    if exit_day.weekday() > 4:
        exit_day = datetime.fromordinal(exit_day.toordinal() + padding_week_day).date()

    exit_dates.append(exit_day)

    assigned_career_manager = career_mgrs[RG.randint(1, len(career_mgrs) -1)]
    assigned_career_mgrs.append(assigned_career_manager)

    exit_interview_date = f.date_between(notice_day, datetime.fromordinal(exit_day.toordinal() -7))

    exit_interviews.append(exit_interview_date)

    RRH_interview_date = f.date_between(exit_interview_date, exit_day)

    RRH_interviews.append(RRH_interview_date)

    reason_leaving = motifs_departs[RG.randint(
        1, len(motifs_departs) - 1)]
    reasons_for_leaving_1.append(reason_leaving)

    reason_leaving = motifs_departs[RG.randint(
        1, len(motifs_departs) - 1)]
    reasons_for_leaving_2.append(reason_leaving)

    experiences_and_strengths = f.sentence(nb_words=7)

    strengths.append(experiences_and_strengths)

    improvement = f.sentence(nb_words=7)
    areas_for_improvement.append(improvement)

    empl_lst = employment_situations[:]
    if age <= 61:
        rm = "Retraité"
        empl_lst.remove("Retraité")
    
    if age >= 62:
        empl_lst.remove("Parent au foyer")

    future_employment = empl_lst[RG.randint(1, len(empl_lst) - 1)]
    future_employment_situations.append(future_employment)

    RRH_comment = f.paragraph(nb_sentences=2)

    commentaires_RRH.append(RRH_comment)



FirstNames_df.insert(0, 'GGID', GGID)
FirstNames_df.insert(4, "Date_de_naissance", dobs)
FirstNames_df.insert(5, "Age", ages)
FirstNames_df.insert(6, "Date_Embauche", start_dates)
FirstNames_df.insert(7, "Ancienneté", service_years)
FirstNames_df.insert(8, "Sites", site_postes)
FirstNames_df.insert(9, "Service_Line", services_posts)
FirstNames_df.insert(10, "Grade", grades)
FirstNames_df.insert(11, "Role", roles_posts)
FirstNames_df.insert(12, "Date_Démission_notification", notice_dates)
FirstNames_df.insert(13, "Date_de_départ_prévue", exit_dates)
FirstNames_df.insert(14, "Carrière_manager", assigned_career_mgrs)
FirstNames_df.insert(15, "Date_entretien_de_départ", exit_interviews)
FirstNames_df.insert(16, "RRH_entretien", RRH_interviews)
FirstNames_df.insert(17, "Motif_départ_1", reasons_for_leaving_1)
FirstNames_df.insert(18, "Motif_départ_2", reasons_for_leaving_2)
FirstNames_df.insert(19, 'Points_forts_expérience_parcours', strengths)
FirstNames_df.insert(20, "Axes_amélioration", areas_for_improvement)
FirstNames_df.insert(21, "Situation_future_entreprise_ou_autre", future_employment_situations)
FirstNames_df.insert(22, "Commentaire_RRH ", commentaires_RRH)

FirstNames_df.set_index('GGID')

# RNG.write_to_csv(FirstNames_df, target_directory=target_dir, target_file=target_file)
# RNG.write_to_xlsx(FirstNames_df, target_directory=target_dir,
#                   target_file=target_file)

#print(FirstNames_df.head())
print(roles_df)
